"""
Training pipeline for the Exercise Analysis LSTM model.

The model learns to classify each timestep of a (T, D) feature sequence into
idle / concentric / eccentric, then a separate state machine (src/model/reps.py)
turns the predicted phase sequence into a rep count with timestamps.

Data:  synthetic feature sequences generated by generate_synthetic_data.py.
       The per-phase feature statistics are measured from each exercise's demo
       render (scripts/make_demo_video.py -> data/phase_stats_<exercise>.json)
       using the same 19-dimensional features Component A extracts, so the
       model learns the *same* input distribution the serving layer feeds it.
       See NOTES.md for the honest caveats.
Split: by video (sequence), never by frame.
Model: unidirectional LSTM by default (causal, so the same weights also serve
       the real-time /v1/stream endpoint).
Runtime: completes on CPU in roughly 5-10 minutes per exercise (default settings).

Usage:
    python train.py                                # push-up, defaults
    python train.py --exercise squat --evaluate    # another exercise
    python train.py --all                          # train every supported exercise
"""
import argparse
import json
import logging
import time
from pathlib import Path

import numpy as np
import torch
from torch.utils.data import DataLoader, Dataset

from src.model.lstm import (
    PushupLSTMLoss,
    create_model,
    masked_accuracy,
    save_checkpoint,
)
from src.model.reps import evaluate_rep_counting
from src.serving.settings import settings

logging.basicConfig(
    level=getattr(logging, settings.log_level),
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)

# exercise id -> (data prefix, checkpoint path)
EXERCISES = {
    "pushup": ("data/train_synthetic", "checkpoints/lstm_pushup.pt"),
    "squat": ("data/train_squat", "checkpoints/lstm_squat.pt"),
    "bicep_curl": ("data/train_bicep_curl", "checkpoints/lstm_bicep_curl.pt"),
    "jumping_jack": ("data/train_jumping_jack", "checkpoints/lstm_jumping_jack.pt"),
}


# ---------------------------------------------------------------------------
# Collate: pad a batch of variable-length sequences, tracking true lengths.
# Padded timesteps get the ignore index (-1) in the target tensor and are
# excluded from the loss and every metric.
# ---------------------------------------------------------------------------
class CollateWithLengths:
    def __init__(self, pad_index: int = -1):
        self.pad_index = pad_index

    def __call__(self, batch):
        features, labels, lengths = zip(*batch)
        max_len = max(lengths)
        feat_dim = features[0].shape[1]

        feat_batch = torch.zeros(len(batch), max_len, feat_dim)
        label_batch = torch.full((len(batch), max_len), self.pad_index, dtype=torch.long)

        for i, (feat, label, n) in enumerate(zip(features, labels, lengths)):
            feat_batch[i, :n] = torch.from_numpy(feat)
            label_batch[i, :n] = torch.from_numpy(np.asarray(label[:n], dtype=np.int64))

        return feat_batch, label_batch, torch.tensor(lengths, dtype=torch.long)


class FeatureSequenceDataset(Dataset):
    """Sequences of (T, D) feature arrays with per-frame phase labels."""

    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return len(self.features)

    def __getitem__(self, idx):
        feat = np.asarray(self.features[idx], dtype=np.float32)
        label = np.asarray(self.labels[idx], dtype=np.int64)
        return feat, label, len(feat)


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------
def train_model(
    epochs: int = 20,
    batch_size: int = 16,
    learning_rate: float = 0.001,
    output_dir: str = "checkpoints",
    device: str = "cpu",
    seed: int = 42,
    checkpoint_path: str = "checkpoints/lstm_pushup.pt",
    val_frac: float = 1.0,
    eval_every: int = 1,
    exercise: str = "pushup",
):
    """Train on the on-disk synthetic splits for an exercise.

    Args:
        val_frac: Fraction of the validation split evaluated each epoch
                  (0-1). Lower values speed up training when runtime is tight.
        eval_every: Evaluate rep-count MAE on validation every N epochs.
        exercise: exercise id (determines the data files; see EXERCISES).
    """
    torch.manual_seed(seed)
    np.random.seed(seed)

    from generate_synthetic_data import load_dataset

    data_prefix, _ = EXERCISES[exercise]

    Path(output_dir).mkdir(parents=True, exist_ok=True)

    train_feats, train_labels = load_dataset(f"{data_prefix}.pkl")
    val_feats, val_labels = load_dataset(f"{data_prefix.replace('train', 'val')}.pkl")
    if val_frac < 1.0:
        n_val = max(1, int(len(val_feats) * val_frac))
        val_feats, val_labels = val_feats[:n_val], val_labels[:n_val]
    logger.info(f"[{exercise}] Loaded {len(train_feats)} train / {len(val_feats)} val sequences")

    train_ds = FeatureSequenceDataset(train_feats, train_labels)
    val_ds = FeatureSequenceDataset(val_feats, val_labels)
    collate = CollateWithLengths()

    train_loader = DataLoader(
        train_ds, batch_size=batch_size, shuffle=True, collate_fn=collate,
    )
    val_loader = DataLoader(
        val_ds, batch_size=batch_size, shuffle=False, collate_fn=collate,
    )

    model = create_model(
        input_dim=settings.feature_dim,
        hidden_size=settings.lstm_hidden_size,
        num_layers=settings.lstm_num_layers,
        dropout=settings.lstm_dropout,
        device=device,
        bidirectional=settings.lstm_bidirectional,
    )
    criterion = PushupLSTMLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

    best_val_mae = float("inf")
    history = []

    start_time = time.time()
    for epoch in range(1, epochs + 1):
        model.train()
        train_loss, train_acc = _run_epoch(
            train_loader, model, criterion, optimizer, device, training=True,
        )

        model.eval()
        val_loss, val_acc = _run_epoch(
            val_loader, model, criterion, None, device, training=False,
        )

        # Rep-count MAE on validation every eval_every epochs (frame preds ->
        # state machine). Cheaper than every epoch.
        if epoch % eval_every == 0 or epoch == epochs:
            val_preds, _ = predict_sequences(model, val_feats, device, max_chunk=None)
            val_metrics = evaluate_rep_counting(val_labels, val_preds, fps=settings.target_fps)
            val_mae = val_metrics["rep_count_mae"]
        else:
            val_mae = history[-1]["val_rep_mae"] if history else 999.0

        history.append({
            "epoch": epoch,
            "train_loss": round(train_loss, 4),
            "train_acc": round(train_acc, 4),
            "val_loss": round(val_loss, 4),
            "val_acc": round(val_acc, 4),
            "val_rep_mae": round(val_mae, 4),
        })
        logger.info(
            f"Epoch {epoch}/{epochs}: "
            f"train_loss={train_loss:.4f} train_acc={train_acc:.4f} | "
            f"val_loss={val_loss:.4f} val_acc={val_acc:.4f} | "
            f"val_rep_mae={val_mae:.4f} ({time.time() - start_time:.0f}s elapsed)"
        )

        config = {
            "input_dim": settings.feature_dim,
            "hidden_size": settings.lstm_hidden_size,
            "num_layers": settings.lstm_num_layers,
            "dropout": settings.lstm_dropout,
            "target_fps": settings.target_fps,
            "epochs": epochs,
            "batch_size": batch_size,
            "lr": learning_rate,
            "seed": seed,
        }
        metrics = {
            "train_loss": train_loss,
            "train_acc": train_acc,
            "val_loss": val_loss,
            "val_acc": val_acc,
            "val_rep_mae": val_mae,
        }
        # Save checkpoint on improved validation rep-count MAE.
        if val_mae < best_val_mae:
            best_val_mae = val_mae
            save_checkpoint(checkpoint_path, model, optimizer, epoch, metrics, config)
            logger.info(f"  saved best checkpoint -> {checkpoint_path} (val MAE {val_mae:.4f})")

    elapsed = time.time() - start_time
    logger.info(f"Training finished in {elapsed:.1f}s ({elapsed / 60:.1f} min)")

    history_path = Path(output_dir) / "history.json"
    with open(history_path, "w") as f:
        json.dump(history, f, indent=2)
    logger.info(f"History written to {history_path}")

    return checkpoint_path


def _run_epoch(loader, model, criterion, optimizer, device, training):
    running_loss = 0.0
    running_acc = 0.0
    n = 0
    for feats, labels, lengths in loader:
        feats, labels, lengths = feats.to(device), labels.to(device), lengths.to(device)
        logits = model(feats, lengths)
        loss = criterion(logits, labels, lengths)
        acc = masked_accuracy(logits, labels, lengths).item()

        if training:
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

        running_loss += loss.item() * len(feats)
        running_acc += acc * len(feats)
        n += len(feats)

    return running_loss / max(n, 1), running_acc / max(n, 1)


@torch.inference_mode()
def predict_sequences(model, features_list, device="cpu", max_chunk=500):
    """Predict phase sequences for a list of feature arrays."""
    preds = []
    model.eval()
    for feats in features_list:
        feats = np.asarray(feats, dtype=np.float32)
        T = feats.shape[0]
        if max_chunk and max_chunk < T:
            # Split long sequences so the LSTM never exceeds window limits.
            outs = []
            for start in range(0, T, max_chunk):
                chunk = feats[start:start + max_chunk]
                x = torch.from_numpy(chunk).unsqueeze(0).to(device)
                lengths = torch.tensor([chunk.shape[0]], device=device)
                outs.append(model(x, lengths).cpu().numpy()[0])
            logits = np.concatenate(outs, axis=0)
        else:
            x = torch.from_numpy(feats).unsqueeze(0).to(device)
            lengths = torch.tensor([T], device=device)
            logits = model(x, lengths).cpu().numpy()[0]
        logits = logits - logits.max(axis=1, keepdims=True)
        exps = np.exp(logits)
        probs = exps / exps.sum(axis=1, keepdims=True)
        preds.append(probs.argmax(axis=1).tolist())
    return preds, None


def evaluate_trained_model(checkpoint_path: str, device: str = "cpu", exercise: str = "pushup"):
    """Evaluate a saved checkpoint on the held-out test split for an exercise."""
    from generate_synthetic_data import load_dataset
    from src.model.lstm import load_checkpoint
    data_prefix, _ = EXERCISES[exercise]
    test_feats, test_labels = load_dataset(f"{data_prefix.replace('train', 'test')}.pkl")
    logger.info(f"[{exercise}] Loaded {len(test_feats)} held-out test sequences")

    model = create_model(
        input_dim=settings.feature_dim,
        hidden_size=settings.lstm_hidden_size,
        num_layers=settings.lstm_num_layers,
        dropout=settings.lstm_dropout,
        device=device,
        bidirectional=settings.lstm_bidirectional,
    )
    load_checkpoint(checkpoint_path, model, device)
    model.eval()

    preds, _ = predict_sequences(model, test_feats, device)
    metrics = evaluate_rep_counting(test_labels, preds, fps=settings.target_fps)

    logger.info("=== Held-out evaluation ===")
    logger.info(f"Per-class F1: {metrics['per_class_f1']}")
    logger.info(f"Macro F1: {metrics['macro_f1']:.4f}")
    logger.info(f"Rep-count MAE: {metrics['rep_count_mae']:.4f}")

    out = {"exercise": exercise,
           "per_class_f1": metrics["per_class_f1"],
           "macro_f1": metrics["macro_f1"],
           "rep_count_mae": metrics["rep_count_mae"],
           "n_test_sequences": len(test_feats)}
    # Per-exercise metrics file so each exercise's numbers survive a --all run.
    metrics_path = Path(checkpoint_path).parent / f"test_metrics_{exercise}.json"
    with open(metrics_path, "w") as f:
        json.dump(out, f, indent=2)
    logger.info(f"Metrics written to {metrics_path}")
    return metrics


def main():
    parser = argparse.ArgumentParser(description="Train the Exercise Analysis LSTM")
    parser.add_argument("--exercise", type=str, default="pushup",
                        choices=list(EXERCISES.keys()),
                        help="which exercise to train (default: pushup)")
    parser.add_argument("--all", action="store_true",
                        help="train all supported exercises sequentially")
    parser.add_argument("--epochs", type=int, default=20)
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--lr", type=float, default=0.001)
    parser.add_argument("--output-dir", type=str, default="checkpoints")
    parser.add_argument("--device", type=str, default="cpu")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--checkpoint-path", type=str, default=None,
                        help="override checkpoint path (default: per-exercise default)")
    parser.add_argument("--val-frac", type=float, default=1.0, help="fraction of val split to evaluate each epoch (0-1)")
    parser.add_argument("--eval-every", type=int, default=1, help="evaluate rep-count MAE every N epochs")
    parser.add_argument("--fast", action="store_true", help="quick run for development (fewer epochs, cheaper eval)")
    parser.add_argument("--evaluate", action="store_true", help="evaluate the final checkpoint on the held-out test split")
    args = parser.parse_args()

    if args.fast:
        args.epochs = min(args.epochs, 6)
        args.val_frac = 0.25
        args.eval_every = 2

    exercises = list(EXERCISES.keys()) if args.all else [args.exercise]

    for exercise in exercises:
        _, default_ckpt = EXERCISES[exercise]
        checkpoint_path = args.checkpoint_path or default_ckpt

        logger.info(
            f"[{exercise}] Training config: epochs={args.epochs}, batch={args.batch_size}, "
            f"lr={args.lr}, device={args.device}, val_frac={args.val_frac}, "
            f"checkpoint={checkpoint_path}"
        )

        checkpoint = train_model(
            epochs=args.epochs,
            batch_size=args.batch_size,
            learning_rate=args.lr,
            output_dir=args.output_dir,
            device=args.device,
            seed=args.seed,
            checkpoint_path=checkpoint_path,
            val_frac=args.val_frac,
            eval_every=args.eval_every,
            exercise=exercise,
        )

        if args.evaluate:
            evaluate_trained_model(checkpoint, device=args.device, exercise=exercise)

    logger.info("Training pipeline finished.")


if __name__ == "__main__":
    main()
